services:
  - type: web
    name: api-generica-investigacion
    env: python
    plan: free
    buildCommand: pip install -r requirements-prod.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DB_PROVIDER
        value: postgres
      - key: DB_POSTGRES
        sync: false